class ProjectsScreenConstants {
  static String starrGEODesc =
      "Starr GEO is a cutting-edge mobile application designed to streamline attendance tracking and shift management with its comprehensive suite of features. Users enjoy seamless attendance capture, including the ability to log breaks for accurate timekeeping. The app facilitates transparency and accountability by allowing users to upload images related to their shifts and add comments for detailed documentation and communication.Furthermore, Starr GEO enhances task management by displaying allocated tasks directly on the staff list, ensuring everyone stays informed and on track. With the convenience of a Finish button, users can effortlessly conclude their shifts, simplifying the process further. Creating shifts is made effortless through the app's QR code integration, enabling users to select available locations with ease. Data security is prioritized, with the application initially storing information in a local database before securely synchronizing it with the main server.To ensure user authenticity and security, Starr GEO implements robust authentication via email ID, providing peace of mind to both users and administrators. With its user-friendly interface and comprehensive features, Starr GEO sets a new standard for efficient and reliable attendance management in various industries.";

  static String starrKeyDesc =
      "Starr Key is an innovative attendance management application tailored to streamline workforce scheduling and tracking. Upon logging in, staff members effortlessly create their shifts by entering a secure 4-digit PIN. The application then displays a comprehensive shift history for easy reference and tracking.The clock-in feature simplifies the start of shifts, with the added functionality of syncing employee photos to ensure accurate verification. Similarly, clocking out is made efficient and straightforward, enhancing the overall user experience.Additionally, Starr Key fosters a collaborative environment by allowing employees to check their colleagues' schedules, facilitating coordination and communication within the team. This feature promotes efficiency and ensures smooth operations across the organization. Starr Key prioritizes data security and integrity by implementing stringent authentication measures and encryption protocols, safeguarding sensitive information at all times. With its intuitive interface and robust features, Starr Key revolutionizes attendance management, empowering organizations to optimize workforce productivity and streamline administrative processes effectively.";

  static String ktRoyalDesc =
      "KT Royal restaurant app offers a seamless dining experience with its intuitive features and user-friendly interface. Authentication is simplified through personal phone number verification, ensuring secure access to the app. Upon setting up their account with necessary details, users are greeted with three convenient options: dine-in, take away, and delivery. In the dine-in section, a unique QR code is provided for each table, enabling users to effortlessly check the status and availability of their chosen table. Once confirmed, the comprehensive menu is displayed, categorized with prices for easy browsing. Users can add desired items to their cart, customizing their order to perfection. With a simple click, orders can be swiftly placed, ensuring a smooth and efficient dining experience. KT Royal prioritizes convenience and efficiency, allowing users to enjoy their favorite dishes with ease. Whether dining in, taking away, or opting for delivery, the app caters to diverse preferences, promising satisfaction with every order. With its seamless functionality and user-centric design, KT Royal restaurant app sets a new standard for dining convenience and enjoyment.";
}
