import 'package:flutter/material.dart';

class ProjectsScreenConstants {
  // COLORS
  static const Color starrGEOImagesLoadColor = Color(0xff393749);
  static Color starrKeyImagesLoadColor = Colors.orange.shade400;
  static const Color shoeaImagesLoadColor = Colors.white70;
  static const Color ktRoyalImagesLoadColor = Color(0xffBC6F15);
  static Color habitTrackerImagesLoadColor = Colors.blueGrey.shade300;

  // DESCRIPTION
  static String starrGEODesc =
      "Starr GEO is a cutting-edge mobile application designed to streamline attendance tracking and shift management with its comprehensive suite of features. Users enjoy seamless attendance capture, including the ability to log breaks for accurate timekeeping. The app facilitates transparency and accountability by allowing users to upload images related to their shifts and add comments for detailed documentation and communication.Furthermore, Starr GEO enhances task management by displaying allocated tasks directly on the staff list, ensuring everyone stays informed and on track. With the convenience of a Finish button, users can effortlessly conclude their shifts, simplifying the process further. Creating shifts is made effortless through the app's QR code integration, enabling users to select available locations with ease. Data security is prioritized, with the application initially storing information in a local database before securely synchronizing it with the main server.To ensure user authenticity and security, Starr GEO implements robust authentication via email ID, providing peace of mind to both users and administrators. With its user-friendly interface and comprehensive features, Starr GEO sets a new standard for efficient and reliable attendance management in various industries.";

  static String starrKeyDesc =
      "Starr Key is an innovative attendance management application tailored to streamline workforce scheduling and tracking. Upon logging in, staff members effortlessly create their shifts by entering a secure 4-digit PIN. The application then displays a comprehensive shift history for easy reference and tracking. The clock-in feature simplifies the start of shifts, with the added functionality of syncing employee photos to ensure accurate verification. Similarly, clocking out is made efficient and straightforward, enhancing the overall user experience.Additionally, Starr Key fosters a collaborative environment by allowing employees to check their colleagues' schedules, facilitating coordination and communication within the team. This feature promotes efficiency and ensures smooth operations across the organization. Starr Key prioritizes data security and integrity by implementing stringent authentication measures and encryption protocols, safeguarding sensitive information at all times. With its intuitive interface and robust features, Starr Key revolutionizes attendance management, empowering organizations to optimize workforce productivity and streamline administrative processes effectively.";

  static String ktRoyalDesc =
      "KT Royal restaurant app offers a seamless dining experience with its intuitive features and user-friendly interface. Authentication is simplified through personal phone number verification, ensuring secure access to the app. Upon setting up their account with necessary details, users are greeted with three convenient options: dine-in, take away, and delivery. In the dine-in section, a unique QR code is provided for each table, enabling users to effortlessly check the status and availability of their chosen table. Once confirmed, the comprehensive menu is displayed, categorized with prices for easy browsing. Users can add desired items to their cart, customizing their order to perfection. With a simple click, orders can be swiftly placed, ensuring a smooth and efficient dining experience. KT Royal prioritizes convenience and efficiency, allowing users to enjoy their favorite dishes with ease. Whether dining in, taking away, or opting for delivery, the app caters to diverse preferences, promising satisfaction with every order. With its seamless functionality and user-centric design, KT Royal restaurant app sets a new standard for dining convenience and enjoyment.";

  static String shoeaDesc =
      "Seamlessly blending elegance with efficiency, Shoea offers users a seamless journey through its meticulously crafted features. With secure email password authentication and optional social login capabilities, users can effortlessly access their accounts, ensuring a personalized and secure experience. Shoea elevates the shopping experience with intuitive functionalities. Users can effortlessly browse through an extensive catalog of shoes, adding desired items to their wishlist or cart with just a tap. The app’s streamlined checkout process allows users to place orders conveniently, specifying delivery addresses and selecting preferred payment methods, including cash on delivery, UPI, or card payments. Beyond the shopping experience, Shoea empowers users with comprehensive order management tools. From tracking ordered items to monitoring their arrival status, users stay informed every step of the way. The app’s sleek profile page offers additional customization options, enabling users to manage their account settings and preferences with ease. For retailers, Shoea offers a separate admin panel application, providing comprehensive management capabilities. Built with efficiency in mind, Shoea utilizes Hive for local storage database, ensuring seamless performance even offline. Additionally, the integration of APIs, backed by Node.js, Express.js, and MongoDB, ensures robust connectivity and scalability. With Shoea, the fusion of elegance and functionality sets a new standard in the realm of e-commerce apps. Whether indulging in the latest footwear trends or managing retail operations, Shoea caters to the diverse needs of modern shoppers and businesses alike.";

  static String habitTrackerDesc =
      "Introducing a groundbreaking Flutter application: your personal Habit Tracker. This innovative app empowers users to cultivate positive habits with ease. Seamlessly integrated with Hive for efficient local storage, users can effortlessly add, delete, complete, and update their habits, fostering a sense of accountability and progress. At the heart of the app lies a dynamic heat map, visually representing users' progress in habit completion. This intuitive feature provides instant insights, motivating users to stay consistent and committed to their goals. With its user-friendly interface and robust functionalities, the Habit Tracker simplifies habit formation, transforming aspirations into tangible achievements. Whether striving for fitness goals, cultivating mindfulness, or enhancing productivity, this app serves as a reliable companion on the journey towards personal growth and success.";
}
